spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  reds:
    host: localhost
    port: 6379
  application:
    name: ssm
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include=*:
