spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
  reds:
    host: localhost
    port: 6379
  application:
    name: ssm
  output:
    ansi:
      enabled: always


management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include=*:
