spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    open-in-view: false

  application:
    name: student-score-management
  output:
    ansi:
      enabled: always
